AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

# Allow reasonable method complexity for orchestration code
Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 120

Style/IfUnlessModifier:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Lint/NonAtomicFileOperation:
  Enabled: false
